git:
  depth: 10
dist: trusty
sudo: required

matrix:
  include:
    - stage: build docker image
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t pubmedminer-api .
        - docker images
        - docker tag pubmedminer-api $DOCKER_ORGANIZATION/pubmedminer-api
        - docker push $DOCKER_ORGANIZATION/pubmedminer-api
      on:
        branch: master
